# House Price Analysis

## Import Libraries

In [1]:
# Import necessary libraries
import pandas as pd

## Load the Data

In [3]:
# Load the dataset (CSV file)

df=pd.read_csv('F:/Ai_26/Libraries/Data/house_prices.csv')

## Explore the Data

In [4]:
# Show first 5 rows
df.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN

- **Task:** Observe the data structure and column types.
- **Reflection:** Write a short note about what each column represents and any observations.

In [5]:
# Number of rows and columns
df.shape

(187531, 21)

In [6]:
# Column names
df.columns

Index(['Index', 'Title', 'Description', 'Amount(in rupees)',
       'Price (in rupees)', 'location', 'Carpet Area', 'Status', 'Floor',
       'Transaction', 'Furnishing', 'facing', 'overlooking', 'Society',
       'Bathroom', 'Balcony', 'Car Parking', 'Ownership', 'Super Area',
       'Dimensions', 'Plot Area'],
      dtype='str')

In [7]:

# General info about all columns
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Title              187531 non-null  str
 2   Description        184508 non-null  str
 3   Amount(in rupees)  187531 non-null  str
 4   Price (in rupees)  169866 non-null  float64
 5   location           187531 non-null  str
 6   Carpet Area        106858 non-null  str
 7   Status             186916 non-null  str
 8   Floor              180454 non-null  str
 9   Transaction        187448 non-null  str
 10  Furnishing         184634 non-null  str
 11  facing             117298 non-null  str
 12  overlooking        106095 non-null  str
 13  Society            77853 non-null   str
 14  Bathroom           186703 non-null  str
 15  Balcony            138596 non-null  str
 16  Car Parking        84174 non-null   str
 17  Ownership          122014 non-null  str
 18  Super Area         79846 non-null   str
 19  Dimensions         0 non-null       float64
 20  Plot Area          0 non-null       float64
dtypes: float64(3), int64(1), str(17)
memory usage: 30.0 MB

In [8]:
# Count of missing values in each column
df.isnull().sum()

Index                     0
Title                     0
Description            3023
Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           80673
Status                  615
Floor                  7077
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Society              109678
Bathroom                828
Balcony               48935
Car Parking          103357
Ownership             65517
Super Area           107685
Dimensions           187531
Plot Area            187531
dtype: int64

- **Task:** Review missing values.
- **Reflection:** Which columns have the most missing data? Which columns are mostly complete? How might missing data affect your analysis?

In [9]:
# Summary statistics for numerical columns
df.describe()

               Index  Price (in rupees)  Dimensions  Plot Area
count  187531.000000       1.698660e+05         0.0        0.0
mean    93765.000000       7.583772e+03         NaN        NaN
std     54135.681003       2.724171e+04         NaN        NaN
min         0.000000       0.000000e+00         NaN        NaN
25%     46882.500000       4.297000e+03         NaN        NaN
50%     93765.000000       6.034000e+03         NaN        NaN
75%    140647.500000       9.450000e+03         NaN        NaN
max    187530.000000       6.700000e+06         NaN        NaN

- **Task:** Review the summary statistics for numeric columns.
- **Reflection:** Write a note on unusual values (like 0 or extremely high numbers) and columns that may need cleaning.

In [12]:
# check for duplicate rows
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
187526    False
187527    False
187528    False
187529    False
187530    False
Length: 187531, dtype: bool

## Data Cleaning

In [19]:
# Fill missing 'Price (in rupees)' with the mean
df['Price (in rupees)'].fillna(
    df['Price (in rupees)'].mean(),
    inplace=True
)

#df.fillna(df.mean(numeric_only=True), inplace=True)
df

C:\Users\mosta\AppData\Local\Temp\ipykernel_24940\2919038505.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Price (in rupees)'].fillna(

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.000000,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.000000,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.000000,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,7583.771885,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.000000,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,187526,3 BHK Ready to Occupy Flat for sale in Bollywo...,This magnificent 3 BHK Flat is available for s...,63 Lac,3225.000000,zirakpur,NaN,Ready to Move,2 out of 4,New Property,...,East,Garden/Park,Bollywood Esencia,3,3,1 Covered,Freehold,1953 sqft,NaN,NaN
187527,187527,3 BHK Ready to Occupy Flat for sale in Sushma ...,Have a look at this immaculate 3 BHK flat for ...,55 Lac,3274.000000,zirakpur,NaN,Ready to Move,4 out of 6,Resale,...,North - East,"Garden/Park, Main Road",Sushma Urban Views,3,NaN,1 Covered,NaN,1680 sqft,NaN,NaN
187528,187528,3 BHK Ready to Occupy Flat for sale in Bollywo...,"Gazipur, Zirakpur has an appealing 3 BHK flat ...",76 Lac,4343.000000,zirakpur,1250 sqft,Ready to Move,1 out of 3,Resale,...,East,"Garden/Park, Main Road",Bollywood Esencia,3,2,"1 Covered,",Freehold,NaN,NaN,NaN
187529,187529,2 BHK Ready to Occupy Flat for sale in Friends...,Up for immediate sale is a 2 BHK apartment in ...,30 Lac,4231.000000,zirakpur,NaN,Ready to Move,2 out of 2,Resale,...,NaN,Main Road,Friends Enclave,2,NaN,NaN,NaN,709 sqft,NaN,NaN
187530,187530,3 BHK Ready to Occupy Flat for sale in Affinit...,This exquisite 3 BHK Flat is offered for sale ...,1.18 Cr,6162.000000,zirakpur,NaN,Ready to Move,5 out of 13,Resale,...,North - East,"Garden/Park, Pool",Affinity Greens,4,4,1 Covered,Freehold,1915 sqft,NaN,NaN

In [ ]:
# Fill missing 'Price (in rupees)' with the mean

In [51]:
# Fill missing 'Carpet Area' with median (safer than mean for skewed data)
####there problem !!!!
#df['Carpet Area'] = df['Carpet Area'].str.replace("sqft","")
df['Carpet Area'] = pd.to_numeric(df['Carpet Area'], errors='coerce')

#df['Carpet Area']=df['Carpet Area'] = df['Carpet Area'].str.replace("sqft","")
df['Carpet Area']

0          500.0
1          473.0
2          779.0
3          530.0
4          635.0
           ...
187526       NaN
187527       NaN
187528    1250.0
187529       NaN
187530       NaN
Name: Carpet Area, Length: 187531, dtype: float64

In [37]:

# Fill missing 'Status' with 'Unknown'
df['Status'] = df['Status'].fillna('Unknown')
df

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.000000,thane,500,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.000000,thane,473,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.000000,thane,779,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,7583.771885,thane,530,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.000000,thane,635,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,187526,3 BHK Ready to Occupy Flat for sale in Bollywo...,This magnificent 3 BHK Flat is available for s...,63 Lac,3225.000000,zirakpur,NaN,Ready to Move,2 out of 4,New Property,...,East,Garden/Park,Bollywood Esencia,3,3,1 Covered,Freehold,1953 sqft,NaN,NaN
187527,187527,3 BHK Ready to Occupy Flat for sale in Sushma ...,Have a look at this immaculate 3 BHK flat for ...,55 Lac,3274.000000,zirakpur,NaN,Ready to Move,4 out of 6,Resale,...,North - East,"Garden/Park, Main Road",Sushma Urban Views,3,NaN,1 Covered,NaN,1680 sqft,NaN,NaN
187528,187528,3 BHK Ready to Occupy Flat for sale in Bollywo...,"Gazipur, Zirakpur has an appealing 3 BHK flat ...",76 Lac,4343.000000,zirakpur,1250,Ready to Move,1 out of 3,Resale,...,East,"Garden/Park, Main Road",Bollywood Esencia,3,2,"1 Covered,",Freehold,NaN,NaN,NaN
187529,187529,2 BHK Ready to Occupy Flat for sale in Friends...,Up for immediate sale is a 2 BHK apartment in ...,30 Lac,4231.000000,zirakpur,NaN,Ready to Move,2 out of 2,Resale,...,NaN,Main Road,Friends Enclave,2,NaN,NaN,NaN,709 sqft,NaN,NaN
187530,187530,3 BHK Ready to Occupy Flat for sale in Affinit...,This exquisite 3 BHK Flat is offered for sale ...,1.18 Cr,6162.000000,zirakpur,NaN,Ready to Move,5 out of 13,Resale,...,North - East,"Garden/Park, Pool",Affinity Greens,4,4,1 Covered,Freehold,1915 sqft,NaN,NaN

In [ ]:
# Drop columns with mostly missing values (>80%)
df=df[df.columns[df.isnull().mean()<0.8]]
#df.dropna(axis=1,how='all',inplace=True)
df

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.000000,thane,500,Ready to Move,10 out of 11,Resale,Unfurnished,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.000000,thane,473,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.000000,thane,779,Ready to Move,10 out of 29,Resale,Unfurnished,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,7583.771885,thane,530,Ready to Move,1 out of 3,Resale,Unfurnished,NaN,NaN,NaN,1,1,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.000000,thane,635,Ready to Move,20 out of 42,Resale,Unfurnished,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,187526,3 BHK Ready to Occupy Flat for sale in Bollywo...,This magnificent 3 BHK Flat is available for s...,63 Lac,3225.000000,zirakpur,NaN,Ready to Move,2 out of 4,New Property,Semi-Furnished,East,Garden/Park,Bollywood Esencia,3,3,1 Covered,Freehold,1953 sqft
187527,187527,3 BHK Ready to Occupy Flat for sale in Sushma ...,Have a look at this immaculate 3 BHK flat for ...,55 Lac,3274.000000,zirakpur,NaN,Ready to Move,4 out of 6,Resale,Unfurnished,North - East,"Garden/Park, Main Road",Sushma Urban Views,3,NaN,1 Covered,NaN,1680 sqft
187528,187528,3 BHK Ready to Occupy Flat for sale in Bollywo...,"Gazipur, Zirakpur has an appealing 3 BHK flat ...",76 Lac,4343.000000,zirakpur,1250,Ready to Move,1 out of 3,Resale,Furnished,East,"Garden/Park, Main Road",Bollywood Esencia,3,2,"1 Covered,",Freehold,NaN
187529,187529,2 BHK Ready to Occupy Flat for sale in Friends...,Up for immediate sale is a 2 BHK apartment in ...,30 Lac,4231.000000,zirakpur,NaN,Ready to Move,2 out of 2,Resale,Semi-Furnished,NaN,Main Road,Friends Enclave,2,NaN,NaN,NaN,709 sqft
187530,187530,3 BHK Ready to Occupy Flat for sale in Affinit...,This exquisite 3 BHK Flat is offered for sale ...,1.18 Cr,6162.000000,zirakpur,NaN,Ready to Move,5 out of 13,Resale,Semi-Furnished,North - East,"Garden/Park, Pool",Affinity Greens,4,4,1 Covered,Freehold,1915 sqft

In [44]:
# Show cleaned data
df.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.000000,thane,500,Ready to Move,10 out of 11,Resale,Unfurnished,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.000000,thane,473,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.000000,thane,779,Ready to Move,10 out of 29,Resale,Unfurnished,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,7583.771885,thane,530,Ready to Move,1 out of 3,Resale,Unfurnished,NaN,NaN,NaN,1,1,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.000000,thane,635,Ready to Move,20 out of 42,Resale,Unfurnished,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN

**Task:** Perform basic data cleaning as shown above.

**Reflection** Questions (write your answers ):

- Which columns did you clean and why?

- Why did you fill Price (in rupees) with the mean instead of dropping rows?

- Why did you fill Carpet Area with the median?

- Why did you fill Status with 'Unknown'?

- Why did we drop columns with mostly missing values (>80%)?

- How do you think these cleaning steps will affect your analysis later?

## Filtering & Sorting Data

In [45]:
# Flats with Price less than 1 Cr
df[df['Price (in rupees)']<10000000]

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.000000,thane,500,Ready to Move,10 out of 11,Resale,Unfurnished,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.000000,thane,473,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.000000,thane,779,Ready to Move,10 out of 29,Resale,Unfurnished,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,7583.771885,thane,530,Ready to Move,1 out of 3,Resale,Unfurnished,NaN,NaN,NaN,1,1,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.000000,thane,635,Ready to Move,20 out of 42,Resale,Unfurnished,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,187526,3 BHK Ready to Occupy Flat for sale in Bollywo...,This magnificent 3 BHK Flat is available for s...,63 Lac,3225.000000,zirakpur,NaN,Ready to Move,2 out of 4,New Property,Semi-Furnished,East,Garden/Park,Bollywood Esencia,3,3,1 Covered,Freehold,1953 sqft
187527,187527,3 BHK Ready to Occupy Flat for sale in Sushma ...,Have a look at this immaculate 3 BHK flat for ...,55 Lac,3274.000000,zirakpur,NaN,Ready to Move,4 out of 6,Resale,Unfurnished,North - East,"Garden/Park, Main Road",Sushma Urban Views,3,NaN,1 Covered,NaN,1680 sqft
187528,187528,3 BHK Ready to Occupy Flat for sale in Bollywo...,"Gazipur, Zirakpur has an appealing 3 BHK flat ...",76 Lac,4343.000000,zirakpur,1250,Ready to Move,1 out of 3,Resale,Furnished,East,"Garden/Park, Main Road",Bollywood Esencia,3,2,"1 Covered,",Freehold,NaN
187529,187529,2 BHK Ready to Occupy Flat for sale in Friends...,Up for immediate sale is a 2 BHK apartment in ...,30 Lac,4231.000000,zirakpur,NaN,Ready to Move,2 out of 2,Resale,Semi-Furnished,NaN,Main Road,Friends Enclave,2,NaN,NaN,NaN,709 sqft
187530,187530,3 BHK Ready to Occupy Flat for sale in Affinit...,This exquisite 3 BHK Flat is offered for sale ...,1.18 Cr,6162.000000,zirakpur,NaN,Ready to Move,5 out of 13,Resale,Semi-Furnished,North - East,"Garden/Park, Pool",Affinity Greens,4,4,1 Covered,Freehold,1915 sqft

In [54]:
# Flats with Carpet Area greater than 600 sqft
df=df[df['Carpet Area']>600]
df['Carpet Area']

2          779.0
4          635.0
9          900.0
10         950.0
13        1820.0
           ...
187522    1200.0
187523    1705.0
187524     895.0
187525    1050.0
187528    1250.0
Name: Carpet Area, Length: 87745, dtype: float64

In [56]:
# Sort by Price descending
df = df.sort_values(by='Price (in rupees)', ascending=False)
df['Price (in rupees)']

181234    6700000.0
176536    4041600.0
174894    3450000.0
175013    2669100.0
174925     322727.0
            ...
183352          0.0
166029          0.0
165311          0.0
174916          0.0
165838          0.0
Name: Price (in rupees), Length: 87745, dtype: float64

In [58]:
# show each data after sorting
#df.head()
df.tail()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area
183352,183352,3 BHK Ready to Occupy Flat for sale surya apar...,This ready to move-in 3 BHK flat is available ...,80 Lac,0.0,varanasi,1160.0,Ready to Move,2 out of 5,Resale,Unfurnished,East,NaN,NaN,2,3,NaN,Freehold,NaN
166029,166029,2 BHK Ready to Occupy Flat for sale Harishanka...,One can find this stunning 2 BHK flat for sale...,45 Lac,0.0,gwalior,800.0,Ready to Move,1 out of 2,Resale,Unfurnished,NaN,NaN,NaN,2,1,NaN,Freehold,NaN
165311,165311,2 BHK Ready to Occupy Flat for sale Dhirenpara,This ready to move-in 2 BHK flat is available ...,48 Lac,0.0,guwahati,1100.0,Ready to Move,2 out of 2,Resale,Unfurnished,NaN,NaN,NaN,2,2,NaN,NaN,NaN
174916,174916,3 BHK Ready to Occupy Flat for sale in Wallfor...,"Bhatgaon, Raipur has an appealing 3 BHK flat f...",78 Lac,0.0,raipur,1750.0,Ready to Move,8 out of 10,Resale,Unfurnished,East,"Garden/Park, Pool",Wallfort Heights,3,2,NaN,Freehold,NaN
165838,165838,3 BHK Ready to Occupy Flat for sale in Ashoka ...,This beautiful 3 BHK Flat is available for sal...,79 Lac,0.0,guwahati,1460.0,Ready to Move,1 out of 4,Resale,Semi-Furnished,East,Main Road,Ashoka Apartment,2,2,NaN,Freehold,NaN

**Task:** Apply filtering and sorting.

**Reflection** Questions:

- Which filters did you apply?

- What did you learn from the sorted data?

- Are there any patterns or outliers?

## Selecting Key Columns

In [63]:
# select the following columns from the cleaned dataset  Title , Price (in rupees), Carpet Area, Status, Floor, location
#df.columns=['Title', 'Price (in rupees)', 'Carpet Area', 'Status', 'Floor', 'location']
selected_columns = ['Title', 'Price (in rupees)', 'Carpet Area', 'Status', 'Floor', 'location']

df = df[selected_columns]

df.head()

,Title,Price (in rupees),Carpet Area,Status,Floor,location
181234,3 BHK Ready to Occupy Flat for sale in Nest Ha...,6700000.0,1252.0,Ready to Move,5 out of 9,vadodara
176536,3 BHK Ready to Occupy Flat for sale Hill Cart ...,4041600.0,970.0,Ready to Move,1 out of 4,siliguri
174894,2 BHK Ready to Occupy Flat for sale Kachna Road,3450000.0,920.0,Ready to Move,2 out of 2,raipur
175013,2 BHK Ready to Occupy Flat for sale in Chaitan...,2669100.0,750.0,Ready to Move,2 out of 9,raipur
174925,2 BHK Ready to Occupy Flat for sale Arya polis...,322727.0,1105.0,Ready to Move,4 out of 4,raipur

**Task:** Focus on key columns.

**Reflection** Questions:

- Why did you select these columns?

- How might they relate to each other in analysis?

## Aggregations & Relationships

In [66]:
# Average price
avr=df['Price (in rupees)'].mean()
avr

np.float64(8321.058533910213)

In [69]:
# Average price by Location
#using groupby
avr_lo=df.groupby('location')['Price (in rupees)'].mean()
avr_lo

location
agra             4542.098844
ahmadnagar       5651.692971
ahmedabad        5918.475592
allahabad        6469.756912
aurangabad       4971.806698
                    ...
varanasi         5449.707188
vijayawada       4779.469304
visakhapatnam    5224.268378
vrindavan        4777.769420
zirakpur         4445.117372
Name: Price (in rupees), Length: 81, dtype: float64

In [70]:
# Min and Max carpet area
df['Carpet Area'].min(), df['Carpet Area'].max()

(np.float64(601.0), np.float64(709222.0))

In [75]:

# Average Price by Status
#using groupby
a = df.groupby('Status')['Price (in rupees)'].mean()
print(a)

Status
Ready to Move    8322.576719
Unknown          6472.394489
Name: Price (in rupees), dtype: float64

In [77]:
# Average Carpet Area by Location
ex=df.groupby('location')['Carpet Area'].mean()
ex

location
agra             3296.350254
ahmadnagar       1073.875000
ahmedabad        1622.814972
allahabad        1057.673077
aurangabad       1429.696429
                    ...
varanasi         1124.760000
vijayawada       1149.123028
visakhapatnam    1208.510545
vrindavan         914.142857
zirakpur         1278.070076
Name: Carpet Area, Length: 81, dtype: float64

**Task:** Calculate aggregations and explore relationships.

**Reflection** Questions:

- What patterns do you see between Price, Carpet Area, Status, and Location?

- Any surprising insights?

## General Questions on Data

In [78]:
# Display the first 10 rows of the cleaned dataset.

df.head(10)

,Title,Price (in rupees),Carpet Area,Status,Floor,location
181234,3 BHK Ready to Occupy Flat for sale in Nest Ha...,6700000.0,1252.0,Ready to Move,5 out of 9,vadodara
176536,3 BHK Ready to Occupy Flat for sale Hill Cart ...,4041600.0,970.0,Ready to Move,1 out of 4,siliguri
174894,2 BHK Ready to Occupy Flat for sale Kachna Road,3450000.0,920.0,Ready to Move,2 out of 2,raipur
175013,2 BHK Ready to Occupy Flat for sale in Chaitan...,2669100.0,750.0,Ready to Move,2 out of 9,raipur
174925,2 BHK Ready to Occupy Flat for sale Arya polis...,322727.0,1105.0,Ready to Move,4 out of 4,raipur
159992,> 10 BHK Ready to Occupy Flat for sale Mapusa,122727.0,2200.0,Ready to Move,Ground out of 2,goa
117607,4 BHK Ready to Occupy Flat for sale Sukhdev Vi...,95000.0,2400.0,Ready to Move,2 out of 4,new-delhi
1921,4 BHK Ready to Occupy Flat for sale Pali Hill,84619.0,2300.0,Ready to Move,NaN,mumbai
114412,4 BHK Ready to Occupy Flat for sale Pali Hill,84619.0,2300.0,Ready to Move,NaN,mumbai
114421,3 BHK Ready to Occupy Flat for sale in Rustomj...,76923.0,1200.0,Ready to Move,9 out of 14,mumbai

In [79]:

# Count the number of flats per Location.
df['location'].value_counts()

location
new-delhi      16355
gurgaon        11589
kolkata         8864
bangalore       7537
hyderabad       6985
               ...
madurai           12
satara            11
pondicherry        9
solapur            9
ahmadnagar         8
Name: count, Length: 81, dtype: int64

In [81]:
# Find the top 5 most expensive flats
#error#top=df.max(numeric_only=True).nlargest(5,'Price (in rupees)')
top_5 = df.nlargest(5, 'Price (in rupees)')
top_5

,Title,Price (in rupees),Carpet Area,Status,Floor,location
181234,3 BHK Ready to Occupy Flat for sale in Nest Ha...,6700000.0,1252.0,Ready to Move,5 out of 9,vadodara
176536,3 BHK Ready to Occupy Flat for sale Hill Cart ...,4041600.0,970.0,Ready to Move,1 out of 4,siliguri
174894,2 BHK Ready to Occupy Flat for sale Kachna Road,3450000.0,920.0,Ready to Move,2 out of 2,raipur
175013,2 BHK Ready to Occupy Flat for sale in Chaitan...,2669100.0,750.0,Ready to Move,2 out of 9,raipur
174925,2 BHK Ready to Occupy Flat for sale Arya polis...,322727.0,1105.0,Ready to Move,4 out of 4,raipur

In [83]:
# Filter all flats where Status = Ready to Move
df[df['Status']=='Ready to Move']
df.head()

,Title,Price (in rupees),Carpet Area,Status,Floor,location
181234,3 BHK Ready to Occupy Flat for sale in Nest Ha...,6700000.0,1252.0,Ready to Move,5 out of 9,vadodara
176536,3 BHK Ready to Occupy Flat for sale Hill Cart ...,4041600.0,970.0,Ready to Move,1 out of 4,siliguri
174894,2 BHK Ready to Occupy Flat for sale Kachna Road,3450000.0,920.0,Ready to Move,2 out of 2,raipur
175013,2 BHK Ready to Occupy Flat for sale in Chaitan...,2669100.0,750.0,Ready to Move,2 out of 9,raipur
174925,2 BHK Ready to Occupy Flat for sale Arya polis...,322727.0,1105.0,Ready to Move,4 out of 4,raipur

In [88]:
# Calculate median Price and compare with mean Price
compare1=df['Price (in rupees)'].median()
compare2=df['Price (in rupees)'].mean()
print("Median Price:", compare1)
print("Mean Price:", compare2)

Median Price: 7296.0
Mean Price: 8321.058533910213

In [89]:
# Explore relationship between Floor and Price
#Ai
floor_price = df.groupby('Floor')['Price (in rupees)'].mean().sort_index()
print(floor_price)

Floor
1                          11905.000000
1 out of 1                  6286.872650
1 out of 10                 8663.108543
1 out of 11                 5123.269505
1 out of 12                 6050.404077
                               ...
Upper Basement out of 5     5278.478292
Upper Basement out of 6     6723.000000
Upper Basement out of 7    16449.428571
Upper Basement out of 8     4363.333333
Upper Basement out of 9    11765.000000
Name: Price (in rupees), Length: 837, dtype: float64

## Now Write a Short Summery of your findings about house price Data

### **Note**
We will continue working with this dataset step by step. All the tasks you have done so far are preparing you for a Mini Data Analysis Project.

In the next Tasks, we will:

- Apply more advanced visualizations.

- Explore relationships between columns more deeply.

- Answer questions and draw insights from the data.

Keep practicing with this cleaned dataset because it will be the base for all your upcoming exercises.🥰